"""Adding create_time colum to Venue and Artist tables

Revision ID: 25f0e75ada15
Revises: 36f434379f79
Create Date: 2020-04-21 16:33:59.273866

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '25f0e75ada15'
down_revision = '36f434379f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('create_time', sa.DateTime(), default=sa.func.now()))
    op.add_column('Venue', sa.Column('create_time', sa.DateTime(), default=sa.func.now()))

    op.execute('UPDATE "Artist" SET create_time = \'2019-04-20 21:30:00\' WHERE create_time IS NULL')
    op.alter_column('Artist', 'create_time', nullable=False)

    op.execute('UPDATE "Venue" SET create_time = \'2019-04-20 21:30:00\' WHERE create_time IS NULL')
    op.alter_column('Venue', 'create_time', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'create_time')
    op.drop_column('Artist', 'create_time')
    # ### end Alembic commands ###
